<template>
  <div class="realtime-policy-page">
    <div class="page-head">
      <div><span class="eyebrow">REALTIME DIAGNOSIS / POLICY</span><h1>实时诊断策略</h1><p>为每个振动测点绑定一个或多个模型，并控制窗口、节流和告警冷却。</p></div>
      <div class="head-actions"><el-tag :type="status.degraded ? 'warning' : 'success'">{{ status.degraded ? '诊断降级' : '实时链路正常' }}</el-tag><el-button icon="el-icon-refresh" :loading="loading" @click="load">刷新</el-button><el-button v-hasPermi="['sensor:diagnosis:realtime:edit']" type="primary" icon="el-icon-plus" @click="open()">新增策略</el-button></div>
    </div>
    <div class="status-grid"><div><small>启用策略</small><strong>{{ status.enabledPolicyCount || 0 }}</strong></div><div><small>缓冲通道</small><strong>{{ status.bufferedChannels || 0 }}</strong></div><div><small>队列深度</small><strong>{{ status.queueDepth || 0 }}</strong></div><div><small>Pending</small><strong>{{ status.pendingCount || 0 }}</strong></div></div>
    <section class="panel"><div class="toolbar"><el-select v-model="query.deviceId" clearable filterable placeholder="全部设备" @change="load"><el-option v-for="item in devices" :key="item.id" :label="`${item.deviceName || item.deviceCode} · ${item.deviceCode}`" :value="item.id" /></el-select><el-select v-model="query.modelType" clearable placeholder="全部模型" @change="load"><el-option label="齿轮" value="gear" /><el-option label="轴承" value="bearing" /></el-select></div><el-table v-loading="loading" :data="rows" stripe><el-table-column label="设备 / 测点" min-width="220"><template slot-scope="scope">{{ deviceLabel(scope.row.deviceId) }}<small class="sub">{{ pointLabel(scope.row.pointId) }}</small></template></el-table-column><el-table-column label="模型" width="120"><template slot-scope="scope"><el-tag size="mini">{{ scope.row.modelType }}</el-tag><small class="sub">{{ scope.row.modelVersion || 'ACTIVE' }}</small></template></el-table-column><el-table-column prop="windowSamples" label="窗口" width="90" /><el-table-column prop="strideSamples" label="步长" width="90" /><el-table-column prop="minIntervalSeconds" label="间隔(s)" width="90" /><el-table-column label="状态" width="90"><template slot-scope="scope"><el-switch v-model="scope.row.enabled" v-hasPermi="['sensor:diagnosis:realtime:edit']" @change="save(scope.row)" /></template></el-table-column><el-table-column label="操作" width="130"><template slot-scope="scope"><el-button v-hasPermi="['sensor:diagnosis:realtime:edit']" type="text" @click="open(scope.row)">编辑</el-button><el-button v-hasPermi="['sensor:diagnosis:realtime:edit']" type="text" class="danger" @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table><pagination v-show="total > 0" :total="total" :page.sync="query.pageNum" :limit.sync="query.pageSize" @pagination="load" /></section>
    <el-dialog :title="form.id ? '编辑实时策略' : '新增实时策略'" :visible.sync="dialogVisible" width="620px"><el-form ref="form" :model="form" :rules="rules" label-width="110px"><el-form-item label="设备" prop="deviceId"><el-select v-model="form.deviceId" filterable @change="form.pointId = null"><el-option v-for="item in devices" :key="item.id" :label="`${item.deviceName || item.deviceCode} · ${item.deviceCode}`" :value="item.id" /></el-select></el-form-item><el-form-item label="测点" prop="pointId"><el-select v-model="form.pointId" filterable><el-option v-for="item in devicePoints" :key="item.id" :label="`${item.pointName || item.pointCode} · CH${item.channelId || '--'}`" :value="item.id" /></el-select></el-form-item><el-form-item label="模型" prop="modelType"><el-select v-model="form.modelType"><el-option label="齿轮" value="gear" /><el-option label="轴承" value="bearing" /></el-select></el-form-item><el-form-item label="模型版本"><el-input v-model="form.modelVersion" placeholder="留空使用 ACTIVE" /></el-form-item><el-row :gutter="12"><el-col :span="8"><el-form-item label="窗口"><el-input-number v-model="form.windowSamples" :min="1024" :max="262144" /></el-form-item></el-col><el-col :span="8"><el-form-item label="步长"><el-input-number v-model="form.strideSamples" :min="1" :max="262144" /></el-form-item></el-col><el-col :span="8"><el-form-item label="间隔(s)"><el-input-number v-model="form.minIntervalSeconds" :min="1" /></el-form-item></el-col></el-row><el-form-item label="告警冷却(s)"><el-input-number v-model="form.alarmCooldownSeconds" :min="0" /></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled" /></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" :rows="2" maxlength="500" /></el-form-item></el-form><span slot="footer"><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="submit">保存</el-button></span></el-dialog>
  </div>
</template>

<script>
import { getDiagnosisOptions } from '@/api/system/bearingDiagnosis'
import { listRealtimeDiagnosisPolicies, getRealtimeDiagnosisStatus, addRealtimeDiagnosisPolicy, updateRealtimeDiagnosisPolicy, removeRealtimeDiagnosisPolicies } from '@/api/system/realtimeDiagnosis'

const emptyForm = () => ({ deviceId: null, pointId: null, modelType: 'gear', modelVersion: '', windowSamples: 5120, strideSamples: 5120, minIntervalSeconds: 30, alarmCooldownSeconds: 300, enabled: false, remark: '' })
export default {
  name: 'RealtimeDiagnosisPolicy',
  data() { return { loading: false, saving: false, dialogVisible: false, rows: [], total: 0, devices: [], points: [], status: {}, query: { pageNum: 1, pageSize: 10, deviceId: null, modelType: null }, form: emptyForm(), rules: { deviceId: [{ required: true, message: '请选择设备', trigger: 'change' }], pointId: [{ required: true, message: '请选择测点', trigger: 'change' }], modelType: [{ required: true, message: '请选择模型', trigger: 'change' }] } } },
  computed: { devicePoints() { return this.points.filter(item => String(item.deviceId) === String(this.form.deviceId)) } },
  created() { this.load() },
  methods: {
    async load() { this.loading = true; try { const [options, policies, status] = await Promise.all([getDiagnosisOptions(), listRealtimeDiagnosisPolicies(this.query), getRealtimeDiagnosisStatus()]); const optionData = options.data || {}; this.devices = optionData.devices || []; this.points = optionData.points || []; this.rows = policies.rows || []; this.total = policies.total || 0; this.status = status.data || {} } finally { this.loading = false } },
    deviceLabel(id) { const item = this.devices.find(value => String(value.id) === String(id)); return item ? (item.deviceName || item.deviceCode) : `设备 ${id || '--'}` },
    pointLabel(id) { const item = this.points.find(value => String(value.id) === String(id)); return item ? (item.pointName || item.pointCode) : `测点 ${id || '--'}` },
    open(row) { this.form = row ? Object.assign({}, row) : emptyForm(); this.dialogVisible = true; this.$nextTick(() => this.$refs.form && this.$refs.form.clearValidate()) },
    save(row) { const payload = Object.assign({}, row); this.saving = true; updateRealtimeDiagnosisPolicy(payload).then(() => this.$modal.msgSuccess('策略已更新')).catch(() => { row.enabled = !row.enabled }).finally(() => { this.saving = false }) },
    submit() { this.$refs.form.validate(async valid => { if (!valid) return; this.saving = true; try { await (this.form.id ? updateRealtimeDiagnosisPolicy(this.form) : addRealtimeDiagnosisPolicy(this.form)); this.$modal.msgSuccess('策略已保存'); this.dialogVisible = false; await this.load() } finally { this.saving = false } }) },
    async remove(row) { await this.$modal.confirm('确认删除该实时诊断策略？'); await removeRealtimeDiagnosisPolicies(row.id); this.$modal.msgSuccess('策略已删除'); await this.load() }
  }
}
</script>

<style scoped>
.realtime-policy-page { min-height: calc(100vh - 84px); padding: 24px; background: #08111d; color: #dbeafe; } .page-head { display:flex; justify-content:space-between; gap:20px; align-items:flex-end; margin-bottom:18px; } .eyebrow { color:#22d3ee; font-size:12px; letter-spacing:.14em; } h1 { margin:8px 0 5px; color:#f8fafc; } .page-head p { margin:0; color:#8293ad; } .head-actions { display:flex; align-items:center; gap:10px; } .status-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:10px; margin-bottom:16px; } .status-grid div,.panel { border:1px solid #20314b; background:#111c30; } .status-grid div { padding:14px 16px; } .status-grid small,.sub { display:block; color:#71839d; font-size:11px; } .status-grid strong { display:block; margin-top:5px; color:#67e8f9; font-size:22px; } .panel { padding:16px; } .toolbar { display:flex; gap:10px; margin-bottom:14px; } .toolbar .el-select { width:220px; } .danger { color:#f87171; } ::v-deep .el-table,::v-deep .el-table tr,::v-deep .el-table th.el-table__cell { background:#111c30; color:#dbeafe; } ::v-deep .el-table td.el-table__cell,::v-deep .el-table th.el-table__cell { border-color:#243650; } ::v-deep .el-input__inner,::v-deep .el-textarea__inner { background:#0b1625; border-color:#30435e; color:#dbeafe; } @media(max-width:760px){.page-head{display:block}.head-actions{margin-top:14px}.status-grid{grid-template-columns:repeat(2,1fr)}.toolbar{display:block}.toolbar .el-select{width:100%;margin-bottom:8px}}
</style>
